version: '3.7'
services:

  apisix:
    image: ${DOCKER_REGISTRY}go-saas-kit-apisix:${DOCKER_TAG:-latest}
    volumes:
      - ./quickstart/configs/apisix/apisix_conf/config.yaml:/usr/local/apisix/conf/config.yaml:ro
      - ./quickstart/configs:/data/conf
    depends_on:
      - user
      - saas

  user:
    image: ${DOCKER_REGISTRY}go-saas-kit-user:${DOCKER_TAG:-latest}
    depends_on:
      - mysqld
      - redis
    volumes:
      - ./quickstart/configs:/data/conf
      - ./quickstart/.assets:/app/.assets
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./user/Dockerfile

  saas:
    image: ${DOCKER_REGISTRY}go-saas-kit-saas:${DOCKER_TAG:-latest}
    depends_on:
      - user
    volumes:
      - ./quickstart/configs:/data/conf
      - ./quickstart/.assets:/app/.assets
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./saas/Dockerfile

  realtime:
    image: ${DOCKER_REGISTRY}go-saas-kit-realtime:${DOCKER_TAG:-latest}
    depends_on:
      - user
    volumes:
      - ./quickstart/configs:/data/conf
      - ./quickstart/.assets:/app/.assets
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./realtime/Dockerfile

  sys:
    image: ${DOCKER_REGISTRY}go-saas-kit-sys:${DOCKER_TAG:-latest}
    depends_on:
      - user
      - saas
    volumes:
      - ./quickstart/configs:/data/conf
      - ./quickstart/.assets:/app/.assets
    command: ["./sys", "-conf", "/data/conf","-seed.menu.path","/data/conf/seed/sys.yaml"]
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./sys/Dockerfile


