version: '3.7'
services:

  pulsar:
    image: "apachepulsar/pulsar:2.10.1"
    command: bin/pulsar standalone
    hostname: pulsar
    volumes:
      - source: ./.temp/pulsardata
        target: /pulsar/data
        type: bind
#      - source: ./.temp/pulsarconf
#        target: /pulsar/conf
#        type: bind
    ports:
      - "6650:6650"
      - "8080:8080"
#    restart: unless-stopped

  pulsar-manager:
    image: "apachepulsar/pulsar-manager:v0.2.0"
    ports:
      - "9527:9527"
      - "7750:7750"
    depends_on:
      - pulsar
    links:
      - pulsar
    environment:
      SPRING_CONFIGURATION_FILE: /pulsar-manager/pulsar-manager/application.properties


#volumes:
#  pulsardata:
#  pulsarconf: