version: '3.7'
services:

  web:
    image: ${DOCKER_REGISTRY}go-saas-kit-web:${DOCKER_TAG:-latest}
    restart: always

  apisix:
    image: ${DOCKER_REGISTRY}go-saas-kit-apisix:${DOCKER_TAG:-latest}
    restart: always
    volumes:
      - ./quickstart/configs/apisix/apisix_conf/config.yaml:/usr/local/apisix/conf/config.yaml:ro
      - ./quickstart/configs/apisix/apisix_conf/apisix.yaml:/usr/local/apisix/conf/apisix.yaml:ro
      - ./quickstart/configs:/usr/local/apisix/kit/conf
    #    depends_on:
    #      - etcd
    ports:
      - "8600:9080"
      - "9091:9091"
      - "9443:9443"
      - "9092"

  api_docs:
    image: ${DOCKER_REGISTRY}go-saas-kit-swagger:${DOCKER_TAG:-latest}
    ports:
      - "8080"
    environment:
      - BASE_URL="/swagger"

  user:
    image: ${DOCKER_REGISTRY}go-saas-kit-user:${DOCKER_TAG:-latest}
    ports:
      - "8500"
      - "8501"
    depends_on:
      - mysqld
    volumes:
      - ./quickstart/configs:/data/conf
      - ./quickstart/.assets:/app/.assets

  saas:
    image: ${DOCKER_REGISTRY}go-saas-kit-saas:${DOCKER_TAG:-latest}
    ports:
      - "8520"
      - "8521"
    depends_on:
      - mysqld
      - user
    volumes:
      - ./quickstart/configs:/data/conf
      - ./quickstart/.assets:/app/.assets

  sys:
    image: ${DOCKER_REGISTRY}go-saas-kit-sys:${DOCKER_TAG:-latest}
    ports:
      - "8530"
      - "8531"
    depends_on:
      - mysqld
      - user
    volumes:
      - ./quickstart/configs:/data/conf
      - ./quickstart/.assets:/app/.assets

  mysqld:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=youShouldChangeThis
      - MYSQL_ROOT_HOST=%
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3406:3306"

volumes:
  mysql_data:
