version: '3.7'
services:

  nginx:
    image: nginx:alpine
    volumes:
     - ./quickstart/nginx.conf:/etc/nginx/nginx.conf
    ports:
     - "8600:8600"
    depends_on:
      - user
      - saas
      - api_docs

  api_docs:
    image: ${DOCKER_REGISTRY}go-saas-kit-swagger:${DOCKER_TAG:-latest}
    ports:
      - "8080"
    environment:
      - BASE_URL="/swagger"

  user:
    image: ${DOCKER_REGISTRY}go-saas-kit-user:${DOCKER_TAG:-latest}
    ports:
      - "8500"
      - "8501"
    depends_on:
      - mysqld
    volumes:
      - ./quickstart/configs:/data/conf
      - ./quickstart/.assets:/app/.assets

  saas:
    image: ${DOCKER_REGISTRY}go-saas-kit-saas:${DOCKER_TAG:-latest}
    ports:
      - "8520"
      - "8521"
    depends_on:
      - mysqld
      - user
    volumes:
      - ./quickstart/configs:/data/conf
      - ./quickstart/.assets:/app/.assets

  mysqld:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=youShouldChangeThis
      - MYSQL_ROOT_HOST=%
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3406:3306"

volumes:
  mysql_data:
