version: '3.7'
services:

  web:
    image: ${DOCKER_REGISTRY}go-saas-kit-frontend:${DOCKER_TAG:-latest}
    restart: on-failure

  api_docs:
    image: ${DOCKER_REGISTRY}go-saas-kit-swagger:${DOCKER_TAG:-latest}
    environment:
      - BASE_URL="/swagger"
    restart: on-failure
    build:
      context: .
      dockerfile: ./openapi/Dockerfile

  apisix:
    image: ${DOCKER_REGISTRY}go-saas-kit-apisix:${DOCKER_TAG:-latest}
    ports:
      - "80:9080" #Http
      - "9091:9091" #Prometheus
      - "9443:9443" #Https
    restart: on-failure
    build:
      context: .
      dockerfile: ./gateway/apisix/Dockerfile


  mysqld:
    image: mysql:8.0
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=youShouldChangeThis
      - MYSQL_ROOT_HOST=%
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3406:3306"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  redis:
    image: redis:6.0
    restart: always
    command: redis-server --requirepass youShouldChangeThis
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 1s
      timeout: 3s
      retries: 30
    ports:
      - "7379:6379"

  etcd:
    image: bitnami/etcd
    restart: always
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd:2379
    ports:
      - "3379:2379"

  dtm:
    image: yedf/dtm:latest
    restart: on-failure
    command: ["-c", "/data/conf.yml"]
    volumes:
      - ./quickstart/configs/dtm/conf.yml:/data/conf.yml
    ports:
      - "36790:36790"
      - "36789:36789"

volumes:
  mysql_data:
  apisix_runner:
  consul_data:
