version: '3.7'
services:

  nginx:
    image: nginx:alpine
    volumes:
     - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
     - "8600:8600"

  api_docs:
    image: ${DOCKER_REGISTRY}go-saas-kit-swagger:${DOCKER_TAG:-latest}
    ports:
      - "8080"

  user:
    image: ${DOCKER_REGISTRY}go-saas-kit-user:${DOCKER_TAG:-latest}
    ports:
      - "8500:8500"
      - "8501:8501"
    depends_on:
      - mysqld
    volumes:
      - ./configs:/data/conf

  saas:
    image: ${DOCKER_REGISTRY}go-saas-kit-saas:${DOCKER_TAG:-latest}
    ports:
      - "8520:8520"
      - "8521:8521"
    depends_on:
      - mysqld
      - user
    volumes:
      - ./configs:/data/conf

  mysqld:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=youShouldChangeThis
      - MYSQL_ROOT_HOST=%
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3406:3306"

volumes:
  mysql_data:
