services:
  servers:
    saas:
      http:
        addr: 0.0.0.0:8520
        timeout: 200s
        cors:
          allowed_origins: ["*"]
          allowed_methods: ["GET", "POST", "PUT", "HEAD", "OPTIONS","DELETE","PATCH"]
      grpc:
        addr: 0.0.0.0:8521
        timeout: 200s
data:
  databases:
    databases:
      saas:
        driver: mysql
        source: root:rZakvdyjAmz73J8p@tcp(127.0.0.1:3309)/saas?parseTime=true