serve:
  cookies:
    same_site_mode: Lax

urls:
  self:
    #publich hydra server
    issuer: http://127.0.0.1:4444
  #consent page
  consent: http://127.0.0.1/user/login
  #login page
  login: http://127.0.0.1/user/login
  #logout page
  logout: http://127.0.0.1/user/login

secrets:
  system:
    - youReallyNeedToChangeThis

oidc:
  subject_identifiers:
    supported_types:
      - pairwise
      - public
    pairwise:
      salt: youReallyNeedToChangeThis
