menus:
  - name: "dashboard"
    path: "/dashboard"
    component: "LAYOUT"
    redirect: "/dashboard/workbench"
    is_preserved: true
    title: "Dashboard"
    icon: "ion:grid-outline"
    meta:
    priority: 0
    children:
      - name: "workbench"
        icon: "ant-design:api-outlined"
        path: "workbench"
        component: "/dashboard/workbench/index"
        title: "Workbench"
        is_preserved: true
      - name: "go_saas_kit"
        icon: "ant-design:api-outlined"
        path: "https://github.com/go-saas/kit"
        title: "GO-SAAS-KIT"
        is_preserved: true
      - name: "go_saas"
        icon: "ant-design:api-outlined"
        path: "https://github.com/Goxiaoy/go-saas"
        title: "GO-SAAS"
        is_preserved: true