services:
  servers:
    default:
      http:
        timeout: 200s
        cors:
          allowed_origins: [ "*" ]
      grpc:
        timeout: 200s
    user:
      http:
        addr: 0.0.0.0:8500
      grpc:
        addr: 0.0.0.0:8501
    saas:
      http:
        addr: 0.0.0.0:8520
      grpc:
        addr: 0.0.0.0:8521
    sys:
      http:
        addr: 0.0.0.0:8530
      grpc:
        addr: 0.0.0.0:8531

  services:
    user:
      grpc_endpoint: user:8501
    saas:
      grpc_endpoint: saas:8521
  clients:
    user:
      client_id: user-golang
      timeout: 200s
    saas:
      client_id: saas-golang
      timeout: 200s
    sys:
      client_id: sys-golang
      timeout: 200s
    apisix:
      client_id: apisix-golang
      timeout: 200s

data:
  endpoints:
    databases:
      default:
        driver: mysql
        source: root:youShouldChangeThis@tcp(mysqld:3306)/mysql?parseTime=true&loc=Local&charset=utf8mb4
    redis:
      default:
        addr: redis:6379
        password: youShouldChangeThis
    email:
      smtp:
        host: localhost
    events:
      saas:
        type: kafka
        addr: kafka:9092
        topic: kit
        group: saas-golang
      user:
        type: kafka
        addr: kafka:9092
        topic: kit
        group: user-golang
      sys:
        type: kafka
        addr: kafka:9092
        topic: kit
        group: sys-golang
  blobs:
    user:
      provider: os
      public_url: http://localhost:8600
      base_path: "assets/user"
      os:
        dir: ".assets"
    saas:
      provider: os
      public_url: http://localhost:8600
      base_path: "assets/saas"
      os:
        dir: ".assets"

user:
  password_score_min: 0
  admin:
    username: admin
    password: "123456"
  permission:
    groups:
      - name: "permission.cms.post"
        def:
          - name: "permission.cms.post.any"
            namespace: "cms.post"
            action: "*"
            internal: true
          - name: "permission.cms.post.read"
            namespace: "cms.post"
            action: "read"
          - name: "permission.cms.post.create"
            namespace: "cms.post"
            action: "create"
          - name: "permission.cms.post.update"
            namespace: "cms.post"
            action: "update"
          - name: "permission.cms.post.delete"
            namespace: "cms.post"
            action: "delete"

saas:
  database:
    - name: user
      template: root:youShouldChangeThis@tcp(mysqld:3306)/user-%s?parseTime=true&loc=Local&charset=utf8mb4

security:
  jwt:
    expire_in: 2592000s #    30 days
    secret: 6efa4458-b245-40a3-9685-6b30d5dcda49
  security_cookie:
    hash_key: gt35ofggk07kdt7ief99bl51avd7pbhe
  oidc:
    hydra:
      admin_url: http://hydra:4445

logging:
  filter:
    - level: INFO

tracing:
  otel:
    grpc: otel-collector:4317