app:
  domain_format: ([-a-z0-9]+)\.saas\.nihaosaoya\.com
services:

  services:
    user:
      grpc_endpoint: user:9081
    saas:
      grpc_endpoint: saas:9081

data:
  endpoints:
    databases:
      default:
        driver: mysql
        source: root:youShouldChangeThis@tcp(mysqld:3306)/kit?parseTime=true&loc=Local&charset=utf8mb4
    redis:
      default:
        addr: redis:6379
        password: youShouldChangeThis
    email:
      smtp:
        host: localhost
    events:
      default:
        type: kafka
        addr: kafka:9092
        topic: kit
        group: golang
      saas:
        group: saas-golang
      user:
        group: user-golang
      sys:
        group: sys-golang
  blobs:
    user:
      provider: os
      public_url: /
      base_path: "assets/user"
      os:
        dir: ".assets"
    saas:
      provider: os
      public_url: /
      base_path: "assets/saas"
      os:
        dir: ".assets"


security:
  jwt:
    expire_in: 2592000s #    30 days
    secret: 6efa4458-b245-40a3-9685-6b30d5dcda49
  security_cookie:
    hash_key: gt35ofggk07kdt7ief99bl51avd7pbhe
  oidc:
    hydra:
      admin_url: http://hydra:4445

logging:
  filter:
    - level: INFO

tracing:
  otel:
    grpc: otel-collector:4317