services:
  servers:
    default:
      http:
        timeout: 200s
        cors:
          allowed_origins: [ "*" ]
      grpc:
        timeout: 200s
    user:
      http:
        addr: 0.0.0.0:8500
        csrf:
          cookie:
            secure: false
      grpc:
        addr: 0.0.0.0:8501
    saas:
      http:
        addr: 0.0.0.0:8520
      grpc:
        addr: 0.0.0.0:8521
    sys:
      http:
        addr: 0.0.0.0:8530
      grpc:
        addr: 0.0.0.0:8531

  services:
    user:
      grpc_endpoint: user:8501
    saas:
      grpc_endpoint: saas:8521
  clients:
    user:
      client_id: user-golang
      timeout: 200s
    saas:
      client_id: saas-golang
      timeout: 200s
    sys:
      client_id: sys-golang
      timeout: 200s
    apisix:
      client_id: apisix-golang
      timeout: 200s

data:
  endpoints:
    databases:
      default:
        driver: mysql
        source: root:youShouldChangeThis@tcp(mysqld:3306)/mysql?parseTime=true

  redis:
    addr: 127.0.0.1:6379
    read_timeout: 0.2s
    write_timeout: 0.2s

  blobs:
    user:
      provider: os
      public_url: http://localhost:8600
      base_path: "assets/user"
      os:
        dir: ".assets"
    saas:
      provider: os
      public_url: http://localhost:8600
      base_path: "assets/saas"
      os:
        dir: ".assets"

user:
  password_score_min: 0
  admin:
    username: admin
    password: youShouldChangeThis@123

security:
  jwt:
    expire_in: 2592000s #    30 days
    secret: 6efa4458-b245-40a3-9685-6b30d5dcda49
  security_cookie:
    hash: gt35ofggk07kdt7ief99bl51avd7pbhe
  oidc:
    hydra:
      admin_url: http://hydra:4445