services:
  registry:
    type: etcd
    endpoint: http://host.docker.internal:3379
  servers:
    user:
      http:
        addr : ":19080"
        endpoint: host.docker.internal:19080
      grpc:
        addr : ":19081"
        endpoint: host.docker.internal:19081
    saas:
      http:
        addr : ":19180"
        endpoint: host.docker.internal:19180
      grpc:
        addr : ":19181"
        endpoint: host.docker.internal:19181
    sys:
      http:
        addr : ":19280"
        endpoint: host.docker.internal:19280
      grpc:
        addr : ":19281"
        endpoint: host.docker.internal:19281
    realtime:
      http:
        addr: ":19380"
        endpoint: host.docker.internal:19380
      grpc:
        addr: ":19381"
        endpoint: host.docker.internal:19381

data:
  endpoints:
    events:
      default:
        addr: host.docker.internal:9094
        type: kafka
    databases:
      default:
        debug: true
        driver: mysql
        source: root:youShouldChangeThis@tcp(host.docker.internal:3406)/kit?parseTime=true
    redis:
      default:
        addrs: ["host.docker.internal:7379"]
        password: youShouldChangeThis