routes:
  -
    uri: /v1/saas/*
    upstream_id: saas-http
  -
    uri: /assets/saas/*
    upstream_id: saas-http

  -
    uri: /swagger*
    upstream_id: api-docs
    plugins:
      ext-plugin-pre-req:
        conf:
          - name: "kit_authz"
            value: "{\"requirement\":[{\"namespace\":\"dev.docs\",\"resource\":\"*\",\"action\":\"*\"}]}"

  -
    uri: /jaeger*
    upstream_id: jaeger
    plugins:
      ext-plugin-pre-req:
        conf:
          - name: "kit_authz"
            value: "{\"requirement\":[{\"namespace\":\"dev.jaeger\",\"resource\":\"*\",\"action\":\"*\"}]}"

  -
    uri: /kafka-ui*
    upstream_id: kafka-ui
    plugins:
      ext-plugin-pre-req:
        conf:
          - name: "kit_authz"
            value: "{\"requirement\":[{\"namespace\":\"dev.events.kafka\",\"resource\":\"*\",\"action\":\"*\"}]}"
      response-rewrite:
        headers:
          X-Frame-Options: ""
  -
    uri: /v1/sys/*
    upstream_id: sys-http

  -
    uri: /v1/*
    upstream_id: user-http

  -
    uri: /assets/user
    upstream_id: user-http

  -
    uri: /*
    upstream_id: web

upstreams:
  -
    id: user-http
    nodes:
      "user:9080": 1
    type: roundrobin

  -
    id: saas-http
    nodes:
      "saas:9080": 1
    type: roundrobin

  -
    id: sys-http
    nodes:
      "sys:9080": 1
    type: roundrobin

  -
    id: api-docs
    nodes:
      "api_docs:8080": 1
    type: roundrobin
  -
    id: web
    nodes:
      "web:8080": 1
    type: roundrobin

  - id: jaeger
    nodes:
      "jaeger-all-in-one:16686": 1
    type: roundrobin

  - id: kafka-ui
    nodes:
      "kafka-ui:8080": 1
    type: roundrobin


global_rules:
  -
    id: 1
    plugins:
      opentelemetry:
        sampler:
          name: always_on
  -
    id: 2
    plugins:
      ext-plugin-pre-req:
        conf:
          - name: "kit_authn"
            value:  "{}"
  -
    id: 3
    plugins:
      cors:
        allow_origins: "*"
#END