name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches:
      - 'main'
  workflow_dispatch:

env:
  DOCKER_TAG: dev

jobs:

  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build the docker image
        run: docker-compose -f docker-compose.yml build

      - name: Docker login
        if: |
          github.event_name == 'push'
          && github.repository == 'Goxiaoy/go-saas-kit'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Push docker image
        if: |
          github.event_name == 'push'
          && github.repository == 'Goxiaoy/go-saas-kit'

        run: docker-compose -f docker-compose.yml push

#      - name: Publish to demo server
#        if: |
#          github.event_name == 'push'
#          && github.repository == 'Goxiaoy/go-saas-kit'
#        uses: appleboy/scp-action@master
#        with:
#          host: ${{ secrets.HOST }}
#          username: ${{ secrets.USERNAME }}
#          password: ${{ secrets.PASSWORD }}
#          port: ${{ secrets.PORT }}
#          source: "quickstart/,.env,docker-compose.yml,docker-compose.tracing.yml,docker-compose.hydra.yml"
#          target: "/app/go-saas-kit"
#      - name: Update demo server
#        if: |
#          github.event_name == 'push'
#          && github.repository == 'Goxiaoy/go-saas-kit'
#        uses: appleboy/ssh-action@master
#        with:
#          host: ${{ secrets.HOST }}
#          username: ${{ secrets.USERNAME }}
#          password: ${{ secrets.PASSWORD }}
#          port: ${{ secrets.PORT }}
#          envs: DOCKER_TAG
#          script: |
#            echo "$DOCKER_TAG"
#            cd /app/go-saas-kit
#            docker-compose -f docker-compose.yml -f docker-compose.tracing.yml pull
#            docker-compose -f docker-compose.yml -f docker-compose.tracing.yml up -d --remove-orphans
     

          
