name: Publish Dev Server CI

on:
  workflow_run:
    workflows: [ "Docker Image CI", "Docker Image Microservice CI" ]
    types:
      - completed
  workflow_dispatch:

env:
  DOCKER_TAG: dev

jobs:

  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Publish to demo server
        if: github.repository == 'go-saas/kit'
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          source: "quickstart/,.env,docker-compose.yml,docker-compose.tracing.yml,docker-compose.kafka.yml,docker-compose.ms.yml"
          target: "/app/go-saas-kit"
      - name: Update demo server
        if: github.repository == 'go-saas/kit'
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          envs: DOCKER_TAG
          script: |
            echo "$DOCKER_TAG"
            cd /app/go-saas-kit
            sudo docker compose -f docker-compose.yml -f docker-compose.tracing.yml -f docker-compose.kafka.yml -f docker-compose.ms.yml pull
            sudo docker compose -f docker-compose.yml -f docker-compose.tracing.yml -f docker-compose.kafka.yml -f docker-compose.ms.yml up -d --remove-orphans
